services:
  cpu:
    build:
      context: .
      args:
        DEVICE: cpu
    ports:
      - "8000:8000"
    profiles: ["cpu"]

  gpu:
    build:
      context: .
      args:
        DEVICE: gpu
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    profiles: ["gpu"]
