services:
  cpu:
    build:
      context: .
      args:
        DEVICE: cpu
    ports:
      - "8000:8000"
    volumes:
      - torch_cache:/root/.cache/torch/hub/checkpoints
    profiles: ["cpu"]

  gpu:
    build:
      context: .
      args:
        DEVICE: gpu
    ports:
      - "8000:8000"
    volumes:
      - torch_cache:/root/.cache/torch/hub/checkpoints
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    profiles: ["gpu"]

volumes:
  torch_cache:
